# Generated by Django 5.0.6 on 2024-08-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isicApp', '0003_remove_chatmessage_message_remove_chatmessage_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='last_graduation_point',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='language',
        ),
        migrations.AddField(
            model_name='application',
            name='baccalaureate_category',
            field=models.CharField(choices=[('Science', 'Science'), ('Literature', 'Literature'), ('Economics', 'Economics')], default='Literature', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='diploma_category',
            field=models.CharField(choices=[('Ordinary License', 'Ordinary License'), ('Professional License', 'Professional License'), ('ISIC Diploma', 'ISIC Diploma')], default='ISIC Diploma', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='diploma_grade',
            field=models.CharField(choices=[('Not Bad', 'Not Bad'), ('Good', 'Good'), ('Very Good', 'Very Good')], default='Good', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='diploma_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('AR', 'Arabic')], default='Arabic', max_length=2),
        ),
        migrations.AddField(
            model_name='application',
            name='semester_1_grade',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='semester_2_grade',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='semester_3_grade',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='semester_4_grade',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='semester_5_grade',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='semester_6_grade',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='field',
            field=models.CharField(choices=[('Political Communication', 'Political Communication'), ('Sports Journalism', 'Sports Journalism'), ('Creativity', 'Creativity')], max_length=50),
        ),
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(choices=[('B', 'Bachelor'), ('M', 'Master')], max_length=1),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
