# Generated by Django 5.0.6 on 2024-08-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isicApp', '0006_alter_competition_field_alter_customuser_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='field',
            field=models.CharField(choices=[('Diplome d`ISIC', 'Journalism'), ('Political Communication', 'Political Communication'), ('Sports Journalism', 'Sports Journalism'), ('Creativity', 'Creativity')], max_length=50, null=True),
        ),
    ]
