# Generated by Django 5.0.6 on 2024-08-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isicApp', '0007_alter_competition_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='diploma_category',
            field=models.CharField(choices=[('Sans diplome', 'Sans diplome'), ('Diplome d`ISIC', 'Diplome d`ISIC'), ('Ordinary License', 'Ordinary License'), ('Professional License', 'Professional License'), ('ISIC Diploma', 'ISIC Diploma')], default='ISIC Diploma', max_length=20),
        ),
        migrations.AlterField(
            model_name='competition',
            name='field',
            field=models.CharField(choices=[('Diplome d`ISIC', 'Diplome d`ISIC'), ('Political Communication', 'Political Communication'), ('Sports Journalism', 'Sports Journalism'), ('Creativity', 'Creativity')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(choices=[('L', 'License'), ('M', 'Master')], max_length=1),
        ),
    ]
