# Generated by Django 5.0.6 on 2024-08-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isicApp', '0009_alter_application_diploma_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='diploma_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
