# Generated by Django 5.0.6 on 2024-08-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isicApp', '0011_application_baccalaureate_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='diploma_category',
            field=models.CharField(blank=True, choices=[('Diplome d`ISIC', 'Diplome d`ISIC'), ('Ordinary License', 'Ordinary License'), ('Professional License', 'Professional License')], max_length=20),
        ),
    ]
