# Generated by Django 5.0.6 on 2024-08-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isicApp', '0013_application_cne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='cne',
            new_name='CNE',
        ),
    ]
