# Generated by Django 5.0.6 on 2024-08-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isicApp', '0015_application_license_field_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Arabic', 'Arabic')], default='AR', max_length=25),
        ),
    ]
