# Generated by Django 5.0.6 on 2024-08-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isicApp', '0016_alter_application_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Arabic', 'Arabic')], max_length=25),
        ),
        migrations.AlterField(
            model_name='application',
            name='université',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
