# Generated by Django 5.0.6 on 2024-08-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isicApp', '0017_alter_application_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='troisieme_lng',
            field=models.CharField(blank=True, choices=[('Anglais', 'Anglais'), ('Espagnole', 'Espagnole'), ('Allemand', 'Allemand'), ('Autre', 'Autre')], max_length=25, null=True),
        ),
    ]
