# Generated by Django 5.0.6 on 2024-08-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isicApp', '0018_application_troisieme_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='diploma_grade',
            field=models.CharField(blank=True, choices=[('Passable', 'Passable'), ('A-Bien', 'A-Bien'), ('Bien', 'Bien'), ('T-Bien', 'T-Bien')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='language',
            field=models.CharField(choices=[('Anglais', 'Anglais'), ('Francais', 'Francais'), ('Arabe', 'Arabe')], max_length=25),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Arrivée', 'Arrivée'), ('En cours', 'En cours'), ('Accepté', 'Accepté'), ('Rejetée', 'Rejetée')], default='Arrivée', max_length=20),
        ),
        migrations.AlterField(
            model_name='competition',
            name='field',
            field=models.CharField(choices=[('Diplome d`ISIC', 'Diplome d`ISIC'), ('Political Communication', 'Political Communication'), ('الصحافة الرياضية', 'الصحافة الرياضية'), ('Creativity', 'Creativity')], max_length=50, null=True),
        ),
    ]
