# Generated by Django 5.0.6 on 2024-08-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isicApp', '0019_alter_application_diploma_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='diploma_category',
            field=models.CharField(blank=True, choices=[('Diplome d`ISIC', 'Diplome d`ISIC'), ('License Fondamentale', 'License Fondamentale'), ('License Professionnelle', 'License Professionnelle')], max_length=60),
        ),
        migrations.AlterField(
            model_name='competition',
            name='field',
            field=models.CharField(choices=[('Diplome d`ISIC', 'Diplome d`ISIC'), ('Communication Politique', 'Communication Politique'), ('Journalisme Sportif', 'Journalisme Sportif'), ('Innovation et Production de Contenus Audiovisuels et Numérique', 'Innovation et Production de Contenus Audiovisuels et Numérique')], max_length=150, null=True),
        ),
    ]
