# Generated by Django 5.0.6 on 2024-08-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isicApp', '0020_alter_application_diploma_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='baccalaureate_category',
            field=models.CharField(choices=[('Sciences', 'Sciences'), ('Littéraire', 'Littéraire'), ('Economie/Gestion', 'Economie/Gestion')], default='Littéraire', max_length=35),
        ),
    ]
