# Generated by Django 5.0.6 on 2024-08-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isicApp', '0021_alter_application_baccalaureate_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='field',
            field=models.CharField(blank=True, choices=[('Communication Politique', 'Communication Politique'), ('Journalisme Sportif', 'Journalisme Sportif'), ('Innovation et Production de Contenus Audiovisuels et Numérique', 'Innovation et Production de Contenus Audiovisuels et Numérique')], max_length=150, null=True),
        ),
    ]
